### ISSUE TITLE
Application Error: ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by zenvisuals** [nraboy/ng-cordova-facebook-example#1]
Hey there!

First of all, thanks for the wonderful example, I have tried implementing it to my Ionic Project.

The Facebook login popup works just fine and I can login, however, I received a error popup saying "Application Error: ERR_CONNECTION_REFUSED" with my access_token and all that in an android emulator and the application just crashed. I put it on to my android phone and received the same error

Have you encountered such error?

**Comment by Kaushick** [comment]
Hi all,

I'm not getting public profile from facebook. My code snippet : 

$cordovaOauth.facebook('my_app_id', ["email", "public_profile"]).then(function(result) {
  console.log('data in first call: ', result); // Getting an object containing access_token and expires_in only
   }, function(error) {
   alert(JSON.stringify(error));
});

Have you encountered such error?

**Comment by nraboy** [comment]
$cordovaOauth.facebook is for Oauth only.  You need to research the Facebook API if you wish to use more features.

This example application uses three of the Facebook API as a learning reference.

Regards,

**Comment by eternalsayed** [comment]
Hi @nraboy : I've had this working previously. However, I updated my ionic and bower recently and since then, it has started failing. The InAppbrowser is installed, the Oauth is initiated on button click, yet it is showing the error page. Any help, please?

**Comment by nraboy** [comment]
What do your logs say?

**Comment by eternalsayed** [comment]
Same as zenvisuals. Anyways, I figured out the issue in using the cordova plugin to integrate native facebook login so I guess I don't need the solution anymore. So thanks! If I needed help again, I sure would let you know.

**Comment by nraboy** [comment]
Override the `redirect_uri` with a hosted URL.  Looks like the latest InAppBrowser doesn't allow localhost anymore.

**Comment by vidimitrov** [comment]
Hi Nick,
Switching to cordova-plugin-inappbrowser@1.1.1 fixed my problem. This is something that is very important to be considered for all the users of the oauth plugin. With the new version of inappbrowser you are getting ERR_CONNECTION_REFUSED for every oauth strategy (in my case Google, LinkedIn and Facebook).
Thanks!

**Comment by nraboy** [comment]
Yes it is a known bug.  I have plans to fix it in a few days.  Since this is a hobby project I don't have all the time in the world to work on it which is why I made it open source, for anyone who wants to contribute as well.

**Comment by jagansai** [comment]
Installing inappbrowser 1.2.1-dev version solved the problem just now. Will be looking forward for the final version. Thank you.

**Comment by nraboy** [comment]
Yes this is being tracked here:

https://github.com/nraboy/ng-cordova-oauth/issues/193

**Comment by rastermax** [comment]
apparently fixed:
https://cordova.apache.org/news/2016/02/04/plugins-release.html
