### ISSUE TITLE
Given URL is not allowed by the Application

### ISSUE THREAD

**Issue by manujbahl** [nraboy/ng-cordova-facebook-example#10]
I followed the setup instructions but when i run the app on emulator i get ..

Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App’s settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App’s domains.

Any idea what this means and how to get around that issue ?

**Comment by nraboy** [comment]
Did you make the Facebook application public in the Facebook dashboard?

**Comment by manujbahl** [comment]
yes ... 
I use the same app for my native iOS project. It works perfectly fine.

**Comment by manujbahl** [comment]
What should we be setting as the websiteurl and callback url in the fb app settings ?

**Comment by nraboy** [comment]
This isn't a native app, it is a web app.  You need to set the oauth callback url to http://localhost/callback

**Comment by manujbahl** [comment]
great that helped .. it logged in in.. Still can not get the profile or the feed.
get request returns a 404 
Object {data: "", status: 404, headers: function, config: Object, statusText: "Not Found"}config: Objectdata: ""headers: function (name) {arguments: (...)get arguments: function ThrowTypeError() { [native code] }set arguments: function ThrowTypeError() { [native code] }caller: (...)get caller: function ThrowTypeError() { [native code] }set caller: function ThrowTypeError() { [native code] }length: 1name: ""prototype: Object__proto__: function Empty() {}<function scope>status: 404statusText: "Not Found"__proto__: Object

when i do the same http request in my browser it works just fine .. and returns the data

**Comment by nraboy** [comment]
Does oauth work?

The errors you get, are those coming from ADB or Xcode?  Where are you obtaining them?

**Comment by joshuarh** [comment]
I'm encountering the same issue here. I have the Google integration working so I know the plugin is set up correctly. 

My Facebook settings are:

- *App Domains*: localhost
- *Site URL*: http://localhost
- *Advanced > Valid OAuth redirect URIs*: http://localhost/callback

Could this have something to do with the fact that Cordova runs using a `file://` URL?

**Comment by joshuarh** [comment]
My mistake -- these settings work correctly, it's just that the response object was different than I expected. So in fact this is a good example of working settings! :+1:

**Comment by joshuarh** [comment]
Just to clarify, I do still receive the warning. However, the OAuth flow works as expected.

**Comment by sadid-khan** [comment]
I m trying to the same. But after logging in I don't get any success or error .
![screenshot_2015-09-16-08-34-05](https://cloud.githubusercontent.com/assets/14312473/9904708/e5d20110-5c4d-11e5-8923-c09810598b64.png) and here Facebook is started running. 
I don't get any response. What I m missing..
Here is my code

**Comment by nraboy** [comment]
See this https://github.com/nraboy/ng-cordova-facebook-example/issues/19.  It is the second report that I've received today.

My guess is Facebook is having problems, but without seeing anyones logs I cannot better advise.

**Comment by sadid-khan** [comment]
After pressing back button i got error " sin in flow cancelled". I started Cordova yesterday. I don't know much about how to log. Seeing ur answer I searched and find log plugin. I m trying to use it. I will provide the log to let you know. Thank you for your quick response.

**Comment by nraboy** [comment]
I just downloaded the repository, built it, and tested it myself. I received no problems which leads me to believe you have an incorrect setup in your Facebook dashboard.

**Comment by sadid-khan** [comment]
<head>
        <meta http-equiv="Content-Security-Policy" content="default-src 'self' data: gap: https://ssl.gstatic.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; media-src *">
        <meta name="format-detection" content="telephone=no">
        <meta name="msapplication-tap-highlight" content="no">
        <meta name="viewport" content="user-scalable=no, initial-scale=1, maximum-scale=1, minimum-scale=1, width=device-width">
        <link rel="stylesheet" type="text/css" href="css/index.css">
        <script src="js/angular.js"></script>
        <script src="js/ngCordova/ng-cordova.js"></script>
        <script type="text/javascript" src="cordova.js"></script>
        <title>Hello World</title>
        <script src="js/app.js"></script>
    </head>
    <body data-ng-app="myApp">
       <div ng-controller="OAuthCtrl">
           <label >
               <button class="button button-block button-positive" ng-click="facebookLogin()">
                   Login with Facebook
               </button>
           </label>
       </div>
    </body>


and the app.js part:


var app = angular.module('myApp', ['ngCordova']);
app.controller("OAuthCtrl", function($scope, $cordovaOauth)
{
    $scope.facebookLogin = function() {
        alert("inside method");
        $cordovaOauth.facebook("758054910972122", ["email","public_profile", "user_friends"]).then(function(result) 
{
            alert("sadid");
            alert(result.data);
            // results
        }, function(error) {
            alert("error");
            alert(error);
            // error
        });
    }

in facebook, i just created the app .
![image](https://cloud.githubusercontent.com/assets/14312473/9926360/a2bd1646-5d36-11e5-933f-2e0030624e25.png)

then settings-> advanced->Client OAuth Settings 
![capture](https://cloud.githubusercontent.com/assets/14312473/9926446/45dea3ee-5d37-11e5-9083-d436a8f02807.PNG)

then what i am missing...??

**Comment by wssantos** [comment]
It's 02:57 here in Brazil and it was driving me crazy. Thank you boys for saving my time. Now I can sleep in peace.
