### ISSUE TITLE
Auto Reload with ionic not working.

### ISSUE THREAD

**Issue by obcdnico** [nraboy/ng-cordova-facebook-example#12]
The app is the same as others.. for me the live reload not working..

I want to use this github for have a new clean based app with very simple facebook login working with android.. thank for this.

why reload not work ? (ionic run android -c-l -s)

**Comment by nraboy** [comment]
You cannot use Live Reload, Ionic View, or Ionic Serve with the ng-cordova-oauth library.  I don't work for Ionic so I don't know why these items perform the way they do.  You may want to open an issue ticket for them or post in the forums.

Regards,
