### ISSUE TITLE
Keyboard is not defined. other ionic not same

### ISSUE THREAD

**Issue by obcdnico** [nraboy/ng-cordova-facebook-example#13]
Can i integrate easily the full process facebook login with simple ionic sidemenu starter ?
(i test it and it is not work easy at moment for me.. facebook connect is sensible)

Very thank to you.. (i'm on a two full Professional version with ionic : first is social and hard, second is simple: connect and reportings.)

other probleme is the standard keyboard not recognised for some angular functionnality
(npm update, node, npm -g (all) )
here my logs..

0     258753   error    Uncaught TypeError: Cannot read property 'Keyboard' of u
ndefined, http://192.168.1.50:8100/js/app.js, Line: 12
1     276864   error    TypeError: Cannot read property 'hide' of undefined
    at Scope.$scope.closeModal (http://192.168.1.50:8100/js/controllers.js:53:23
)
    at http://192.168.1.50:8100/lib/ionic/js/ionic.bundle.js:18471:21
    at http://192.168.1.50:8100/lib/ionic/js/ionic.bundle.js:43026:9
    at Scope.$eval (http://192.168.1.50:8100/lib/ionic/js/ionic.bundle.js:20326:
28)
    at Scope.$apply (http://192.168.1.50:8100/lib/ionic/js/ionic.bundle.js:20424
:23)
    at HTMLDivElement.<anonymous> (http://192.168.1.50:8100/lib/ionic/js/ionic.b
undle.js:43025:13)
    at http://192.168.1.50:8100/lib/ionic/js/ionic.bundle.js:10478:10
    at forEach (http://192.168.1.50:8100/lib/ionic/js/ionic.bundle.js:7950:18)
    at HTMLDivElement.eventHandler (http://192.168.1.50:8100/lib/ionic/js/ionic.
bundle.js:10477:5)
    at triggerMouseEvent (http://192.168.1.50:8100/lib/ionic/js/ionic.bundle.js:
2648:7)

very thank.. if the app can be integrate in ionic standard project.. is very helpfull.. i can share with you some tricks ;-)..

thx.

**Comment by nraboy** [comment]
I'm sorry, but you're asking many things that should be directed at the Ionic team either in the forums or in their issue tracker.

This Facebook example **WILL NOT** work with Ionic Serve, Ionic Reload, or Ionic View.  Based on `http://192.168.1.50:8100/` it is very obvious you are using one of those.

I encourage you to follow the directions I placed in the README or on my relevant blog post:

https://blog.nraboy.com/2015/02/make-facebook-mobile-app-ionic-framework/

That is as much support as I can offer you.

Regards,

**Comment by obcdnico** [comment]
Very Thank to your time in week-end..
Tank a lot.. :)
Le 13 juin 2015 15:33, Nic Raboy <notifications@github.com> a écrit :I'm sorry, but you're asking many things that should be directed at the Ionic team either in the forums or in their issue tracker.

This Facebook example WILL NOT work with Ionic Serve, Ionic Reload, or Ionic View.  Based on http://192.168.1.50:8100/ it is very obvious you are using one of those.

I encourage you to follow the directions I placed in the README or on my relevant blog post:

https://blog.nraboy.com/2015/02/make-facebook-mobile-app-ionic-framework/

That is as much support as I can offer you.

Regards,
