### ISSUE TITLE
Picture size

### ISSUE THREAD

**Issue by Radmess** [nraboy/ng-cordova-facebook-example#15]
Is there any way to get another profile picture size? It seems to only come in 50x50p.
In the non-plugin version of the API, it looks like you set the picture with type=normal. 
Is that possible here?

Thanks in advance.

**Comment by nraboy** [comment]
You'll have to look at the Facebook API documentation.  I just provided this example to show ng-cordova-oauth working.  I can't offer support on the Facebook APIs.

Regards,

**Comment by ammichael** [comment]
I know it's closed a while now, but someone else might have the same question (like I just had).

The way you do it:

`fields: "picture.type(large)"`
