### ISSUE TITLE
How do I surpass this screen please

### ISSUE THREAD

**Issue by Piusn** [nraboy/ng-cordova-facebook-example#18]
![screenshot 2015-08-17 07 55 09](https://cloud.githubusercontent.com/assets/925985/9298331/a5a8da78-44b5-11e5-812c-66cef66f7d44.png)

**Comment by nraboy** [comment]
It is from a race condition.  Your device is displaying the non-existent web page before it processes it.  In most cases this doesn't happen.

I encourage you to update the ng-cordova-oauth library in the project and / or override the redirect_uri in the plugin to a page other than localhost.

Regards,

**Comment by Piusn** [comment]
I decide to use java to develop for android. Thanks!
