### ISSUE TITLE
App Not Setup: The developers of this app have not set up this app properly for Facebook Login.

### ISSUE THREAD

**Issue by mzarella** [nraboy/ng-cordova-facebook-example#2]
Hi Nra, I was able to get the google oauth working! \o/

When I try logging in with facebook, the error I get with this app is 

```
App Not Setup: The developers of this app have not set up this app properly for Facebook Login.
```

At https://developers.facebook.com/apps/:APP_ID/settings/basic/ I have the app domains set to `localhost`, I don't have anything in the "Namespace" field. The Site URL is `http://localhost/`, the Mobiel Site URL is `http://localhost/`

In https://developers.facebook.com/apps/:APP_ID/settings/advanced/ I have Valid OAuth redirect URIs set to `http://localhost/callback`

I'm not sure what else to do, if you have time, this would be a huge help. First time I've ever tried using oauth with Google or Facebook

**Comment by nraboy** [comment]
You only need to register the callback and get an app id.  There isn't anything else to it.

I encourage you to read the official Facebook documentation for help on this as there are no issues with the Oauth at the moment.

Regards,

**Comment by mzarella** [comment]
@nraboy and others who may have a problem: Not only do you need a proper callback, but you also have to indicate that you would like to make your app public. There may be a way around this, but right now, the solution is to go into "Status & Review" and move the slider to indicate that you would like to make the app public.

**Comment by nraboy** [comment]
Thanks for sharing the extra info
