### ISSUE TITLE
An uncaught exception occurred and has been reported to Ionic

### ISSUE THREAD

**Issue by Flyingprinter** [nraboy/ng-cordova-facebook-example#21]
Hmm..

When i do ionic serve.

It wont serve 

ionic $ An uncaught exception occurred and has been reported to Ionic

listen EADDRINUSE 127.0.0.1:8100 (CLI v1.6.5)

Your system information:

Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 1.0.0-beta.13
Ionic CLI Version: 1.6.5
Ionic App Lib Version: 0.3.9
ios-deploy version: Not installed
ios-sim version: 5.0.1
OS: Mac OS X Yosemite (i'm on Captain not Yosemite)
Node Version: v4.1.1
Xcode version: Xcode 7.0.1 Build version 7A1001

**Comment by nraboy** [comment]
Per the documentation of the ng-Cordova-oauth library, ionic serve is incompatible.

Best,

**Comment by kingleroyg** [comment]
I'm also getting the same error:

ionic $ An uncaught exception occurred and has been reported to Ionic

listen EADDRINUSE 127.0.0.1:8100 (CLI v1.7.0)

Your system information:

Cordova CLI: 5.3.3
Gulp version:  CLI version 3.9.0
Gulp local:
Ionic Version: 1.1.0
Ionic CLI Version: 1.7.0
Ionic App Lib Version: 0.5.1-beta.0
OS: Windows 7 SP1
Node Version: v4.1.1

**Comment by nraboy** [comment]
I need your full logs

**Comment by kingleroyg** [comment]
Hi nraboy, I think I just fixed it.... I had too many ionic process running at the same time.... I tried "killall ionic" to kill running ionic processes but to no avail. I had to restart my system but worked perfectly afterwords

**Comment by nraboy** [comment]
If you're using "killall ionic" you're doing it wrong.  Per my README on ng-cordova-oauth, I state you cannot use ionic serve, ionic view, ionic live-reload, or phonegap build.  Seeing that you're killing a server, i know for a fact you're using one of those.
