### ISSUE TITLE
White Blank Screen & Login Question

### ISSUE THREAD

**Issue by Flyingprinter** [nraboy/ng-cordova-facebook-example#22]
Hi, 

I'm getting a White screen after clicking on the sign in button, IOS.

Question , if my app has got Facebook logged in , will it still direct me to the browser to login?

**Comment by nraboy** [comment]
What do your logs say?

The ng-cordova-oauth library is sandboxed.  It has no communication to the native Facebook app or any other app that might be signed in with Facebook.

Regards,

**Comment by Cooknick** [comment]
I'm having the same problem. The Log say initially: 

```
webView:didFailLoadWithError - -1200: An SSL error has occurred and a secure connection to the server cannot be made.
```

After a few minutes it spits out:

```
 MobileSafari[15118]: Communications error: <OS_xpc_error: <error: 0x10db43b40> { count = 1, contents =
    "XPCErrorDescription" => <string: 0x10db43ef0> { length = 22, contents = "Connection interrupted" }
}>
```

This may be a possible solution here, saying it's something with iOS 9... http://stackoverflow.com/questions/32755674/ios9-getting-error-an-ssl-error-has-occurred-and-a-secure-connection-to-the-ser

**Comment by Cooknick** [comment]
The solution I posted above works.

**Comment by akilah007** [comment]
It shows nothing.. Only white freeze screen

**Comment by nraboy** [comment]
Without logs I cannot help you, sorry.  If you're getting ATS related errors like @cooknick mentioned see this:

https://blog.nraboy.com/2015/10/fix-ios-9-app-transport-security-issues-in-apache-cordova/
