### ISSUE TITLE
Facebook Login window not closing after login

### ISSUE THREAD

**Issue by akilah007** [nraboy/ng-cordova-facebook-example#23]
Facebook Login window not closing after login.. Not Redirecting 
This was occurred when using ionic latest

**Comment by nraboy** [comment]
What do your logs say?

**Comment by akilah007** [comment]
Facebook login window popup again after login..
It happen only when I updated the latest ionic version.
ionic lib update

**Comment by nraboy** [comment]
Again, what do your logs say?

**Comment by moussasarr** [comment]
How do I set the proper redirect uri and site uri in my developer.facebook ?  Tried localhost:8000. Is it https://www.facebook.com/connect/login_success.html if I am accessing it from cordova ? Sorry I am just so new to angular and cordova.

**Comment by nraboy** [comment]
Port 8000 is incorrect.  By default it is http://localhost/callback as mentioned in the README.  If you want to override it you can use the optional {redirect_uri: ""} parameter.

Anything having to do with the Facebook dashboard, you'll have to read the Facebook docs.

Regards,
