### ISSUE TITLE
Have a problem with the URLS

### ISSUE THREAD

**Issue by angelrdgz** [nraboy/ng-cordova-facebook-example#24]
Facebook response: Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or canvas URL, or the domain must be a subdomain of one of the Apps's domains.

**Comment by nraboy** [comment]
You did not configure your Facebook dashboard correctly.  You need to add valid oauth callback URLs in the Settings -> Advanced section of Facebook.

I encourage you to read the Facebook documentation for making use of their APIs.

Best,
