### ISSUE TITLE
Could not find inAppBrowser plugin

### ISSUE THREAD

**Issue by cabbabu** [nraboy/ng-cordova-facebook-example#25]
HI Nic,

I have building another app using cordovaOauth and i was getting the error Could not find inAppBrowser plugin for facebook authentication. I tried this sample app it also gives me the same error. Could you please advise what am i missing.

Thanks,
Arvind

**Comment by nraboy** [comment]
This is a known issue with the latest version of Apache Cordova.  Myself and another guy are working as quick as possible to correct it.

In the mean time either, downgrade your Cordova version, or sit patiently for a fix.

Best,

**Comment by babitabhandari** [comment]
I have an issue when i click oAuth button.Errors are as follows
Refused to load the script 'http://localhost:35730/livereload.js?snipver=1' because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-inline' 'unsafe-eval'".

**Comment by nraboy** [comment]
@cabbabu the latest ng-cordova-oauth version fixes this issue.  @babitabhandari if you're using live-reload it will not work.

Best,
