### ISSUE TITLE
could you please tell me the right settings of the app on developers.facebook.com/ ?

### ISSUE THREAD

**Issue by M-H-M-A** [nraboy/ng-cordova-facebook-example#29]
![2](https://cloud.githubusercontent.com/assets/8623734/15269231/c3374052-19f8-11e6-8f10-4b4459c1eade.jpg)
![1](https://cloud.githubusercontent.com/assets/8623734/15269236/f4c639c0-19f8-11e6-8391-6b4f0187069c.jpg)
![screenshot_2016-05-14-17-13-47](https://cloud.githubusercontent.com/assets/8623734/15269238/fdd3050c-19f8-11e6-8854-a3daf53fa0e4.png)

**Comment by nraboy** [comment]
You'll have to read the Facebook documentation.  I can see already from your screenshot though that you did not add http://localhost/callback as one of your redirect uris.

Duplicate ticket found here:

https://github.com/nraboy/ng-cordova-oauth/issues/251

**Comment by M-H-M-A** [comment]
thank you for your fast response.what i am facing now .. Facebook returned error_code=100:Invalid permissions

**Comment by nraboy** [comment]
Again, you'll have to read the provider specific documentation, in this case Facebook.  A quick Google Search lead me to this:

https://developers.facebook.com/docs/facebook-login/permissions

For further help with the Facebook APIs, please use the appropriate Facebook support channels (forums, knowledgebase, docs, etc.).  These are Facebook errors.

Regards,

**Comment by M-H-M-A** [comment]
thank you. it was very helpful. it works correctly both of Facebook and Twitter  but today with "$cordovaOauth.twitter" i got undefined problem and it was work perfectly yesterday . so please help me and sorry for bothering you.
