### ISSUE TITLE
Malfunction on new version of ngCordova

### ISSUE THREAD

**Issue by gqferreira** [nraboy/ng-cordova-facebook-example#30]
When ngCordova are updated to v0.1.27, the example show error on ngCordova injection:

`facebookExample.controller("LoginController", function($scope, $cordovaOauth, $localStorage, $location) //<-- show "Error: [$injector:unpr] Unknown provider: $cordovaOauthProvider <- $cordovaOauth <-"`

**Comment by nraboy** [comment]
ngCordova and ngCordovaOauth are two different libraries.  You need to be using the oauth library.

Best,

**Comment by gqferreira** [comment]
I downloaded your example and just updated the ngCordova.

**Comment by nraboy** [comment]
Ah my mistake.  So oauth was removed from Ionic's version of ngCordova which is currently bundled in this project.  You'll have to download ng-cordova-oauth and include it.

Best,
