### ISSUE TITLE
App says the url is not correct

### ISSUE THREAD

**Issue by shaulhadar** [nraboy/ng-cordova-facebook-example#4]
Hi Nick! great job with this cool project.
I tried using it and did everything, but when trying to login the app, it says that the url is not correct..

I changed the uri to: http://localhost/callback
but i am not sure i did it right... does the reference for " callback" means i need to put something else in the end there?  or is it copy paste and without editing?  because that's what i did and it didn't work for some reason... perhaps there are any additional step that need to be done?

Thanks for your time,
Shaul.

**Comment by nraboy** [comment]
My library expects that you used exactly `http://localhost/callback` during setup in your Facebook dashboard.  You must also make sure your Facebook app is set to public.

I encourage you to read the Facebook documentation for setting up a new app.

Regards,
