### ISSUE TITLE
How to post / share a link

### ISSUE THREAD

**Issue by tariqwebstar** [nraboy/ng-cordova-facebook-example#5]
oauth is working perfectly. I want to share a custom link or post on feed. how to achieve this by using your code  ?

**Comment by nraboy** [comment]
You would have to read the API documentation for the service you're trying to use.  I've only provided the oauth step and don't offer support for APIs.

If you're having trouble with the API documentation, I suggest you post to the appropriate forum board or on StackOverflow.

Regards,

**Comment by tariqwebstar** [comment]
thanks...
