### ISSUE TITLE
Receiving a 404 after logging in but i can access the url in the browser

### ISSUE THREAD

**Issue by joshbedo** [nraboy/ng-cordova-facebook-example#9]
So i came across this tonight, the authentication was successful and i start to go to the `ProfileCtrl` but then an alert displays saying `There was a problem getting your profile.  Check the logs for details.` so i then use `chrome://inspect` to check the console of the application and see the image below. It shows the request was sent and returned a 404 but if i copy the link and open it in a tab i see all of the associated profile information :skull: 

![](https://api.monosnap.com/rpc/file/download?id=7oo3hzfG5sBxIlyvJvnoqYFGfwXxvK)

**Comment by nraboy** [comment]
Hey, so someone brought this up on one of my blog articles, but I forgot which one.  Apparently, Apache made some major changes in their latest release which prevents HTTP requests from performing correctly.  There is a plugin you must install to get it working again.

I will dig for the information and report back.

Thanks,

**Comment by joshbedo** [comment]
Awesome thanks i appreciate it :)

**Comment by nraboy** [comment]
Can you try this:

https://github.com/apache/cordova-plugin-whitelist

Word on the street is that this Apache Cordova plugin will fix your problems in the latest version of Apache Cordova.

Let me know how it goes.

Thanks,

**Comment by joshbedo** [comment]
Yeah sure, i'll give this a shot in the afternoon.

**Comment by nraboy** [comment]
You might want to take a look at this ticket: https://github.com/nraboy/ng-cordova-oauth/issues/75#issuecomment-101083345

I was able to use the library in a fresh project without white-listing.  Did you have any further luck?

Regards,

**Comment by nraboy** [comment]
Oops, disregard that.  I forgot that you had oauth working.  It was the REST APIs with problems.

I think white-listing may still help you.

**Comment by nraboy** [comment]
I just committed https://github.com/nraboy/ng-cordova-facebook-example/commit/ec2d25becb863718f776c610d1a66a2ddae73569

I personally tested that the white-list plugin fixes all the issues.

**Comment by joshbedo** [comment]
Sweet, i'll try to give this a try later.
